# Generated by Django 2.2.6 on 2019-11-21 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True)),
                ('y', models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True)),
                ('stringLocation', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('difficaullty', models.IntegerField(default=0)),
                ('quality', models.IntegerField(default=0)),
                ('grade_rate', models.IntegerField(default=0)),
                ('overall_score', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('notebook', models.BooleanField(default=False)),
                ('attendance', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/universities')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='rate.Location')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('overall_score', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('food_rate', models.IntegerField(default=0)),
                ('security_rate', models.IntegerField(default=0)),
                ('location_rate', models.IntegerField(default=0)),
                ('facility_rate', models.IntegerField(default=0)),
                ('internet_rate', models.IntegerField(default=0)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.University')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('professor_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.ProfessorRate')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.University')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
