# Generated by Django 2.2.6 on 2019-11-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='professor_rate',
        ),
        migrations.AddField(
            model_name='professorrate',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', related_query_name='tags', to='rate.Tag'),
        ),
    ]
