# Generated by Django 2.2.6 on 2019-12-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_auto_20191123_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='professorrate',
            name='total_score',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='universityrate',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
