# Generated by Django 2.2.6 on 2019-12-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_auto_20191209_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professorrate',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', related_query_name='tags', to='rate.Tag'),
        ),
    ]
