# Generated by Django 2.2.6 on 2019-12-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='context',
            field=models.CharField(max_length=1000),
        ),
    ]
